require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'RNAula04Mines' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RNAula04MinesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.93.0', 'Flipper-Folly' => '2.6.7', 'Flipper-DoubleConversion' => '3.1.7' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNAula04Mines-tvOS' do
  # Pods for RNAula04Mines-tvOS

  target 'RNAula04Mines-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
